const fs=require('fs'),path=require('path');const {playwright,browserPath}=require('./browser-runtime.cjs');
(async()=>{
 const base=process.env.CUOTI_QA_URL;if(!base||!/^http:\/\/127\.0\.0\.1:\d+$/.test(base)||base.endsWith(':8765'))throw Error('Set CUOTI_QA_URL to an isolated local test server, not port 8765.');
 const browser=await playwright().chromium.launch({headless:true,...(browserPath()?{executablePath:browserPath()}:{})});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const req=async(route,body,method='POST',subject='english')=>{const r=await page.request.fetch(base+'/api/'+route,{method,headers:{'X-Cuoti-Client':'local-v1','X-Cuoti-Subject':subject},...(body===undefined?{}:{data:body})});if(!r.ok())throw Error(await r.text());return r.json();};
 const boot=await req('bootstrap',undefined,'GET');if(boot.config.configured||!boot.data_dir.replace(/\\/g,'/').includes('/qa-'))throw Error('QA requires an isolated qa-* data directory with no API Key.');
 const out=path.resolve(process.env.CUOTI_QA_OUT||'test-results/browser');fs.mkdirSync(out,{recursive:true});let shots=0;
 const go=async(route)=>{await page.goto(base+'/#/'+route);await page.reload();await page.locator('#main h1,#main h2').first().waitFor();await page.waitForTimeout(150);};
 const shot=async(name)=>{await page.locator('#toast').evaluate(x=>x.hidden=true);await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});shots++;};
 await go('home');if(!boot.profile){await shot('01-setup');await page.locator('[name="nickname"]').fill('验收学生（合成）');await page.locator('button[type="submit"]').click();await page.waitForTimeout(300);}
 await go('home');if(await page.locator('[data-act="choose-subject"]').count()!==7)throw Error('Expected seven subjects');await shot('courses');await page.locator('[data-id="english"]').click();await page.waitForURL('**/#/dashboard');await page.waitForTimeout(200);await shot('02-home-empty');
 const sample=await req('sample',{});const s=await req('sources/'+sample.id,undefined,'GET'),q=s.questions[0];const sid=s.id,kid=q.knowledge[0].id;
 const d=await req('dashboard',undefined,'GET');if(d.active_session)await req('review/sessions/'+d.active_session.id+'/state',{action:'finish'});
 for(const [route,name]of [['dashboard','03-home'],['upload','04-upload'],['source/'+sid+'/status','05-status'],['source/'+sid+'/check','06-check'],['source/'+sid+'/analysis','07-analysis'],['history','08-history'],['question/'+q.id,'09-question'],['knowledge','10-knowledge'],['point/'+kid,'11-point'],['plan','12-plan'],['source/'+sid+'/view','13-source'],['settings','16-settings']]){await go(route);if(route==='settings')await page.locator('.panel p').evaluateAll(xs=>xs.forEach(x=>{if(x.textContent.includes('数据目录：'))x.textContent='数据目录：本机隔离测试目录（不包含学生实际资料）';}));await shot(name);}
 await go('source/'+sid+'/check?q='+q.id);await page.locator('[name="stem"]').fill(q.stem);await page.locator('[data-form="question"] button[type="submit"]').click();await page.waitForTimeout(200);
 await go('plan');await page.locator('[data-act="start-review"]').click();await page.waitForURL('**/#/practice/*');await page.locator('[data-act="reveal"]').waitFor();await shot('14-practice-hidden');
 const reviewId=page.url().split('/practice/')[1];const hidden=await req('review/sessions/'+reviewId,undefined,'GET');if(hidden.items.some(i=>'answer' in i.snapshot))throw Error('Hidden answer returned');
 await page.locator('[data-act="pause-session"]').click();await page.waitForURL('**/#/home');await page.locator('[data-act="choose-subject"]').first().waitFor();await go('practice/'+reviewId);await page.locator('[data-act="resume-session"]').click();await page.waitForTimeout(250);
 await page.locator('[data-act="hint"]').click();await page.waitForTimeout(200);await page.locator('[data-act="reveal"]').click();await page.waitForTimeout(200);await shot('15-practice-answer');if(!await page.locator('[data-act="attempt"][data-result="right"]').isDisabled())throw Error('Hint allows independent right');await page.locator('[data-result="hint"][data-act="attempt"]').click();await page.waitForTimeout(250);
 while(page.url().includes('/practice/')){await page.locator('[data-act="reveal"]').click();await page.waitForTimeout(150);await page.locator('[data-result="wrong"][data-act="attempt"]').click();await page.waitForTimeout(250);}
 await page.waitForURL('**/#/result/*');await page.locator('#main h1,#main h2').first().waitFor();await shot('17-result');
 for(const file of ['math-work.jpg','math-scan.pdf','math-formula.docx']){await go('upload');await page.locator('#file-input').setInputFiles(path.resolve('tests/fixtures/'+file));await page.locator('[name="name"]').fill('文件管道合成样本 '+file);await page.locator('button[type="submit"]').click();await page.waitForURL('**/#/source/*/status');await page.waitForFunction(()=>document.querySelector('#main')?.textContent.includes('资料预览 · 已完成'),{},{timeout:30000});}
 await go('home');await page.locator('[data-id="math"]').click();await page.waitForURL('**/#/dashboard');await page.waitForTimeout(150);await shot('math-dashboard');await go('upload');if(!await page.locator('#main').textContent().then(t=>t.includes('归属学科：数学')))throw Error('Subject switch failed');await shot('math-upload');await go('history');if(await page.locator('#main').textContent().then(t=>t.includes('英语专题')))throw Error('English source leaked');await shot('math-history');await go('knowledge');if(!await page.locator('#main').textContent().then(t=>t.includes('暂未开放')))throw Error('Wrong subject knowledge');
 await page.setViewportSize({width:390,height:844});await go('home');await shot('mobile-courses');await page.locator('[data-id="english"]').click();await page.waitForURL('**/#/dashboard');for(const [r,n]of [['dashboard','mobile-home'],['source/'+sid+'/analysis','mobile-analysis'],['knowledge','mobile-knowledge'],['settings','mobile-settings']]){await go(r);if(r==='settings')await page.locator('.panel p').evaluateAll(xs=>xs.forEach(x=>{if(x.textContent.includes('数据目录：'))x.textContent='数据目录：本机隔离测试目录';}));await shot(n);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('Mobile overflow '+r);}
 if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({passed:true,screenshots:shots,checked:['seven subjects','subject isolation','all pages','image/PDF/DOCX','question save','pause/resume','hidden answers','hint protection','review completion','mobile']}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
